In [1]:
# from pathlib import Path
# import sys

# project_root = Path.cwd().parent  # notebooks -> project root
# sys.path.insert(0, str(project_root))

# from clinical_synopsis.embedder import Embedder
# print("embedder import OK")

# to avoid clinical_synopsis.embedder
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root / "clinical_synopsis"))

from embedder import Embedder
print("embedder import OK")

embedder import OK

In [2]:
import rag as rag

# Look at the first chunk we have in the vector index, take the patient_id attached to that chunk:
pid = rag.vector_documents[0]["patient_id"]

result = rag.rag(
    query="What oncology-related events are documented?",
    patient_id=pid,
    search_type="hybrid",
    num_results=5,
)

len(result["search_results"]), result["search_results"][:2]

(5,
 [{'id': '6e3f2f8c188a50ec8d84a45b499a14a631fcc414',
   'chunk_id': '6e3f2f8c188a50ec8d84a45b499a14a631fcc414',
   'patient_id': '03b93198-d95e-c385-c3a7-80470f411d18',
   'document_id': 'eacfd84f2024e811caae390e056a4e52fefc5249',
   'doc_type': 'oncology_timeline',
   'title': 'Oncology Timeline: Aurora248 Dooley940',
   'heading': 'Oncology Timeline: Aurora248 Dooley940',
   'chunk_text': '- Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18\n- Oncology-related dated events: 52',
   'chunk_index': 0,
   'is_oncology': '1',
   'date_start': '',
   'date_end': '',
   'rrf_score': 0.01639344262295082},
  {'chunk_id': 'f50d5c213d71cb54157be1dbe78d05ff2cb23489',
   'patient_id': '03b93198-d95e-c385-c3a7-80470f411d18',
   'document_id': '304ddea3daed73b3c0c0f47535fef1906ea22987',
   'doc_type': 'oncology_timeline_events',
   'title': 'oncology_timeline_events.csv',
   'heading': 'oncology_timeline_events',
   'chunk_text': "event_type: Observation; date: 2015-10-01T05:29:59-04:00; label: Cancer Disease Progression; status: Patient's condition improved; resource_id: 3ee3c67c-a4a3-37e1-e49b-f20f32cc14db; source_file: data/prototype/sample50/Aurora248_Dooley940_03b93198-d95e-c385-c3a7-80470f411d18.json",
   'chunk_index': 48,
   'is_oncology': 1,
   'date_start': '2015-10-01T05:29:59-04:00',
   'date_end': '2015-10-01T05:29:59-04:00',
   'semantic_score': 0.6768816032454379,
   'rrf_score': 0.01639344262295082}])

In [3]:
print("Answer cost (USD):", result["answer_total_cost_usd"])
print("Eval cost (USD):  ", result["eval_total_cost_usd"])
print("Overall cost (USD):", result["overall_total_cost_usd"])

print("Answer tokens (in/out/total):",
      result["prompt_tokens"],
      result["completion_tokens"],
      result["total_tokens"])

print("Eval tokens (in/out/total):",
      result["eval_prompt_tokens"],
      result["eval_completion_tokens"],
      result["eval_total_tokens"])

Answer cost (USD): 0.00315075
Eval cost (USD):   0.0022897499999999997
Overall cost (USD): 0.005440499999999999
Answer tokens (in/out/total): 1951 375 2326
Eval tokens (in/out/total): 2453 100 2553

In [4]:
for i, doc in enumerate(result["search_results"], start=1):
    print("=" * 80)
    print("Rank:", i)
    print("Chunk ID:", doc.get("chunk_id"))
    print("Patient ID:", doc.get("patient_id"))
    print("Doc type:", doc.get("doc_type"))
    print("Title:", doc.get("title"))
    print("Heading:", doc.get("heading"))
    print("Text:", doc.get("chunk_text", "")[:500])

================================================================================
Rank: 1
Chunk ID: 6e3f2f8c188a50ec8d84a45b499a14a631fcc414
Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
Doc type: oncology_timeline
Title: Oncology Timeline: Aurora248 Dooley940
Heading: Oncology Timeline: Aurora248 Dooley940
Text: - Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
- Oncology-related dated events: 52
================================================================================
Rank: 2
Chunk ID: f50d5c213d71cb54157be1dbe78d05ff2cb23489
Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
Doc type: oncology_timeline_events
Title: oncology_timeline_events.csv
Heading: oncology_timeline_events
Text: event_type: Observation; date: 2015-10-01T05:29:59-04:00; label: Cancer Disease Progression; status: Patient's condition improved; resource_id: 3ee3c67c-a4a3-37e1-e49b-f20f32cc14db; source_file: data/prototype/sample50/Aurora248_Dooley940_03b93198-d95e-c385-c3a7-80470f411d18.json
================================================================================
Rank: 3
Chunk ID: 561c5809a7e9251705306dee52b08e9fd64721ce
Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
Doc type: oncology_timeline
Title: Oncology Timeline: Aurora248 Dooley940
Heading: Timeline
Text: - 2009-10-21T08:03:53-04:00 — Condition: Acute myeloid leukemia, disease (disorder); detail: resolved; resource_id: 08368c45-4529-29c5-de26-9fe4cb93a024
- 2009-10-21T08:03:53-04:00 — Procedure: Chemotherapy (procedure); detail: completed; resource_id: 53bda7eb-3df5-9806-a7bd-7c2e83da1057
- 2014-08-13T08:03:53-04:00 — Condition: Malignant neoplasm of breast (disorder); detail: active; resource_id: 2cd2a53c-aeb1-e49e-6510-e3f41cb29f2a
- 2014-08-13T08:48:17-04:00 — Procedure: Biopsy of breast (proc
================================================================================
Rank: 4
Chunk ID: 51d949ee8fd0b0ec85af8248865036f9ec36bf1b
Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
Doc type: oncology_timeline_events
Title: oncology_timeline_events.csv
Heading: oncology_timeline_events
Text: event_type: Observation; date: 2016-09-21T06:18:26-04:00; label: Cancer Disease Progression; status: Patient's condition improved; resource_id: 034ceafd-6b4e-a30f-7961-ec024dc9b640; source_file: data/prototype/sample50/Aurora248_Dooley940_03b93198-d95e-c385-c3a7-80470f411d18.json
================================================================================
Rank: 5
Chunk ID: e0c9e5bbd81a00a11d224d6db67969a0c4459494
Patient ID: 03b93198-d95e-c385-c3a7-80470f411d18
Doc type: oncology_timeline
Title: Oncology Timeline: Aurora248 Dooley940
Heading: Timeline
Text: 306d
- 2014-08-13T09:21:48-04:00 — Observation: Regional lymph nodes.clinical [Class] Cancer; detail: N0 category (finding); resource_id: a19a959c-f1bd-f17c-00c3-cffa80715283
- 2014-08-14T23:39:48-04:00 — Observation: Stage group.clinical Cancer; detail: Stage 1 (qualifier value); resource_id: 18ac1d97-67f0-8e35-2d61-46bc492b6b20
- 2014-08-14T23:39:48-04:00 — Observation: HER2 [Presence] in Breast cancer specimen by FISH; detail: Negative (qualifier value); resource_id: c04ca034-7fe0-2f4b-9016-a

In [5]:
available_patient_ids = sorted({doc["patient_id"] for doc in rag.vector_documents})
len(available_patient_ids), available_patient_ids[:10]

(50,
 ['03b93198-d95e-c385-c3a7-80470f411d18',
  '0c0f2095-e8ab-7ac4-6ef4-625748255480',
  '0f5704ee-b38b-5a68-449d-9c44806517d0',
  '188e1f01-15b7-d51b-c76d-bdd7772a10e9',
  '25197dc8-9425-1999-5914-f2171b0d4e32',
  '263375ec-5856-81b8-9e51-1cb8e8bcba30',
  '29f6beee-162f-0113-7884-72245814693f',
  '397b2de6-ccd8-858f-bf4a-b6fc379589bd',
  '3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678',
  '3af995f1-02a5-07ee-5a7e-e2470a017f1e'])

# 9 patients for ground truth

We pick 9 patients with 3 from each complexity bucket (low, medium, high) for the ground-truth set, in order to cover simple, medium, and complex EHRs.

`n_resources` is the total number of FHIR resources in that patient’s bundle — i.e., how many individual clinical records (Patient, Encounter, Observation, Condition, Procedure, MedicationRequest, DiagnosticReport, etc.) are contained in the JSON file for that patient.

So we see that the higher `n_resources`, the higher `complexity_score`

Remember:
### Note on COMPLEXITY SCORES for each patient

A higher complexity score should reflect more encounters, conditions, procedures, meds, reports for a given patient, as well as a longer follow-up period (e.g., Febrile neutropenia condition gives a clear date (onsetDateTime, recordedDate) and is tied to an encounter, which contributes to follow-up and complexity).

In `sample_mcode_patients.py` a complexity score is computed as:
```python
complexity_score = (
    counts["Encounter"] * 3
    + counts["Observation"] * 1
    + counts["Condition"] * 2
    + counts["Procedure"] * 2
    + counts["MedicationRequest"] * 2
    + counts["MedicationAdministration"] * 2
    + counts["DiagnosticReport"] * 2
    + min(followup_days // 180, 20)
)
```
Which means that:
- Each resource type contributes with a **weight**:
  - Encounters: \(3 \times\) number of encounters (heavier weight).
  - Observations: \(1 \times\) number of observations.
  - Conditions, Procedures, MedicationRequest, MedicationAdministration, DiagnosticReport: each \(2 \times\) their counts.
- Plus a **time component**:
  - `followup_days` is the difference between the first and last clinical dates found in the bundle.
  - `followup_days // 180` converts follow-up into “half-year blocks”.
  - This term is capped at 20, so very long records don’t dominate.

In [6]:
import pandas as pd

manifest_path = project_root / "data" / "processed" / "mcode_breast_sample_50_manifest.csv"

# Load manifest
df = pd.read_csv(manifest_path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (50, 17)

Columns:
['filename', 'patient_id', 'patient_name', 'n_resources', 'n_encounters', 'n_observations', 'n_conditions', 'n_procedures', 'n_medication_requests', 'n_medication_administrations', 'n_diagnostic_reports', 'first_date', 'last_date', 'followup_days', 'complexity_score', 'complexity_bucket', 'sample_seed']

In [7]:
df

,filename,patient_id,patient_name,n_resources,n_encounters,n_observations,n_conditions,n_procedures,n_medication_requests,n_medication_administrations,n_diagnostic_reports,first_date,last_date,followup_days,complexity_score,complexity_bucket,sample_seed
0,data/raw/longitudinalMCODEBreast/Corrie32_Boyl...,d65197b3-056a-2136-b584-77f43c29da3f,Corrie32 Boyle917,230,27,80,2,27,20,0,28,2020-12-18T03:22:18-05:00,2022-05-20T18:36:55-04:00,518,317,low,42
1,data/raw/longitudinalMCODEBreast/Florine959_St...,f3739580-797d-ae04-eebf-aeddb2fc2f64,Florine959 Stark857,261,25,119,5,23,11,0,26,2019-06-11T21:25:37-04:00,2022-06-21T05:03:45-04:00,1105,330,low,42
2,data/raw/longitudinalMCODEBreast/Deana43_Baumb...,3f130449-d7db-f118-5bd0-cce81084e911,Deana43 Baumbach677,431,42,206,10,23,18,0,44,2012-12-18T03:09:54-05:00,2022-04-12T04:24:54-04:00,3402,540,low,42
3,data/raw/longitudinalMCODEBreast/Joni720_Stied...,43c173b0-172c-f414-5c62-1bdf4bb33954,Joni720 Stiedemann542,459,47,218,17,29,5,0,51,2014-04-22T07:35:47-04:00,2022-05-17T21:08:31-04:00,2947,579,low,42
4,data/raw/longitudinalMCODEBreast/Santos184_Jas...,64ae3769-65e4-222e-6793-1a3bc14ec682,Santos184 Jaskolski867,468,45,241,4,31,11,0,48,2010-08-02T09:36:48-04:00,2022-05-17T22:36:39-04:00,4306,584,low,42
5,data/raw/longitudinalMCODEBreast/Mónica985_Se...,4736727e-63f4-071a-1516-a49310f5a052,Mónica985 Serrato62,436,61,151,6,54,8,0,62,2018-01-07T15:16:05-05:00,2022-04-21T02:52:37-04:00,1564,602,low,42
6,data/raw/longitudinalMCODEBreast/Maryellen651_...,af3bd539-de27-28d9-9016-f1643d4615c0,Maryellen651 Zboncak558,514,54,238,11,35,18,0,56,2011-08-29T07:05:19-04:00,2022-04-27T18:02:46-04:00,3894,660,low,42
7,data/raw/longitudinalMCODEBreast/Darcie474_Fra...,568ec0af-94fa-521b-012e-88f61f78028f,Darcie474 Frami345,496,69,180,2,59,11,0,71,2015-10-27T05:01:54-04:00,2022-04-25T17:02:50-04:00,2372,686,low,42
8,data/raw/longitudinalMCODEBreast/Jani266_Thiel...,3e693a9a-de55-de2e-aab9-500036bcf04b,Jani266 Thiel172,629,76,258,8,67,14,0,80,2011-05-02T16:40:40-04:00,2022-06-03T06:55:38-04:00,4049,844,low,42
9,data/raw/longitudinalMCODEBreast/Dolores502_Ca...,6fb374e8-33aa-a5ea-f050-b61394dfcb99,Dolores502 Caldera106,872,101,305,13,165,18,1,111,2006-05-18T17:21:05-04:00,2022-06-30T17:36:05-04:00,5887,1244,low,42
10,data/raw/longitudinalMCODEBreast/Aurora248_Doo...,03b93198-d95e-c385-c3a7-80470f411d18,Aurora248 Dooley940,1168,150,375,26,203,19,1,173,1997-10-24T08:03:53-04:00,2022-06-10T08:18:53-04:00,8995,1689,low,42
11,data/raw/longitudinalMCODEBreast/Emilia403_Bec...,ee23ebc7-cc3c-862c-03bc-46e9321c0df1,Emilia403 Becerra708,1186,163,390,27,193,16,0,191,1972-09-07T06:28:15-04:00,1998-12-17T05:43:15-05:00,9597,1753,low,42
12,data/raw/longitudinalMCODEBreast/Inga743_Dietr...,deea7c91-1fca-a3a2-6c68-c7acced25766,Inga743 Dietrich576,1224,168,382,33,211,11,0,187,1998-07-11T12:04:25-04:00,2022-02-02T11:19:25-05:00,8607,1790,low,42
13,data/raw/longitudinalMCODEBreast/Clotilde434_R...,188e1f01-15b7-d51b-c76d-bdd7772a10e9,Clotilde434 Rolfson709,1556,191,525,40,287,27,1,225,1988-09-06T09:08:42-04:00,2022-06-16T14:17:14-04:00,12336,2278,low,42
14,data/raw/longitudinalMCODEBreast/Willene254_Fr...,6e424da5-2702-49de-4046-868580fe7235,Willene254 Fritsch593,1774,200,529,57,426,38,0,243,1978-10-09T01:15:56-04:00,2022-06-27T02:22:52-04:00,15967,2677,low,42
15,data/raw/longitudinalMCODEBreast/Enoch803_Will...,dc9e689d-cf14-a7a6-f97c-b117d3b37bb2,Enoch803 Willms744,2016,143,1030,76,273,29,0,259,1945-01-10T10:35:24-04:00,2009-01-07T09:50:24-05:00,23373,2753,low,42
16,data/raw/longitudinalMCODEBreast/Alison204_Bee...,25197dc8-9425-1999-5914-f2171b0d4e32,Alison204 Beer512,1824,267,498,36,345,38,0,299,1994-05-02T11:16:07-04:00,2022-03-21T11:31:07-04:00,10185,2755,low,42
17,data/raw/longitudinalMCODEBreast/Eula461_Crook...,29f6beee-162f-0113-7884-72245814693f,Eula461 Crooks415,1854,231,571,42,408,17,0,284,1980-05-15T13:47:05-04:00,2022-06-02T15:31:45.696000-04:00,15358,2786,medium,42
18,data/raw/longitudinalMCODEBreast/Beth967_Cremi...,41681ed6-efc5-94c0-1bc0-f60b34dbd31b,Beth967 Cremin516,1843,197,565,56,465,41,0,250,1974-04-10T22:48:26-04:00,2022-05-09T04:37:02-04:00,17560,2800,medium,42
19,data/raw/longitudinalMCODEBreast/Vince741_Scha...,cf018f86-f6b8-12a1-9f4d-ba14ff081fb4,Vince741 Schaefer657,2205,143,1057,95,328,57,0,290,1960-05-14T02:35:55-04:00,2022-06-06T04:13:58-04:00,22668,3046,medium,42
20,data/raw/longitudinalMCODEBreast/Leola603_Berg...,ea1bb640-7aef-892b-cc6e-e67763472bf4,Leola603 Bergstrom287,2143,281,631,57,443,37,0,347,1972-06-21T18:23:06-04:00,2022-06-22T20:14:17.349000-04:00,18263,3262,medium,42
21,data/raw/longitudinalMCODEBreast/Lela622_Helle...,940b81eb-27fb-52d3-251e-df6edb18d893,Lela622 Heller342,2255,273,807,57,330,77,4,345,1985-01-17T00:50:50-05:00,2022-05-29T07:52:06-04:00,13646,3272,medium,42
22,data/raw/longitudinalMCODEBreast/Deeann517_Tor...,aee216e6-cbe8-eaf2-3241-4bd1e8a01494,Deeann517 Torp761,2191,287,597,50,500,45,0,336,1984-06-18T18:08:50-04:00,2022-05-31T19:08:50-04:00,13861,3340,medium,42
23,data/raw/longitudinalMCODEBreast/Brigette230_L...,0f5704ee-b38b-5a68-449d-9c44806517d0,Brigette230 Lehner980,2503,177,1187,87,359,52,4,309,1963-12-30T05:03:27-05:00,2022-04-09T22:26:10-04:00,21285,3360,medium,42
24,data/raw/longitudinalMCODEBreast/Shaunda110_Os...,c8061ac1-e8a9-c418-d797-ed46ad7d1b46,Shaunda110 Osinski784,2258,270,712,56,471,78,1,330,1956-05-02T10:46:25-04:00,2006-12-13T10:01:25-05:00,18487,3414,medium,42
25,data/raw/longitudinalMCODEBreast/Whitley172_Fl...,0c0f2095-e8ab-7ac4-6ef4-625748255480,Whitley172 Flatley871,2352,214,857,78,492,93,1,308,1975-07-18T02:31:59-04:00,2022-04-03T23:23:37-04:00,17061,3463,medium,42
26,data/raw/longitudinalMCODEBreast/Esteban536_D'...,e9450780-a5c5-9294-21a6-e1209e619d97,Esteban536 D'Amore443,2533,184,1053,88,588,19,1,320,1954-10-10T01:13:02-05:00,2022-01-16T04:14:41.356000-05:00,24570,3657,medium,42
27,data/raw/longitudinalMCODEBreast/Val761_Weber6...,b9b9379e-68a1-49a5-4292-5cc3380e30d2,Val761 Weber641,2470,244,722,52,790,30,0,308,1975-12-10T16:43:09-05:00,2022-03-25T16:28:29-04:00,16906,3834,medium,42
28,data/raw/longitudinalMCODEBreast/Nanette893_Re...,b3b16cf2-f908-ee52-cf3c-7d0613304da6,Nanette893 Reinger292,2392,256,530,49,918,17,1,293,1985-04-14T21:50:57-05:00,2022-03-08T22:05:57-05:00,13477,3874,medium,42
29,data/raw/longitudinalMCODEBreast/Tory770_Willi...,b31cb2e6-f4db-0f20-43e7-6ab691c2a32b,Tory770 Williamson769,2961,174,1579,116,372,63,1,382,1951-07-06T11:51:01-04:00,2022-05-06T13:36:40.850000-04:00,25872,3989,medium,42
30,data/raw/longitudinalMCODEBreast/Lindsey52_Sha...,397b2de6-ccd8-858f-bf4a-b6fc379589bd,Lindsey52 Shanahan202,2866,172,1257,88,653,100,3,332,1938-03-15T15:42:57-05:00,2007-01-09T15:57:57-05:00,25137,4145,medium,42
31,data/raw/longitudinalMCODEBreast/Tamala194_Rom...,c457bf0f-0a34-2ebf-cec6-a385fb33d8a8,Tamala194 Romaguera67,2890,240,1219,85,503,134,1,374,1973-03-12T09:35:16-05:00,2022-06-03T16:15:17-04:00,17980,4153,medium,42
32,data/raw/longitudinalMCODEBreast/Delpha270_Tre...,263375ec-5856-81b8-9e51-1cb8e8bcba30,Delpha270 Tremblay80,2956,307,1044,96,629,32,0,442,1953-03-25T04:37:40-05:00,2021-10-14T06:46:28-04:00,25040,4383,medium,42
33,data/raw/longitudinalMCODEBreast/Francina926_V...,ecc4a7d0-8838-36b4-44ba-676d5a1f7927,Francina926 Von197,2945,262,970,115,760,71,1,394,1947-04-19T16:36:51-05:00,2022-05-18T17:51:51-04:00,27423,4458,high,42
34,data/raw/longitudinalMCODEBreast/Rosetta750_St...,3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,Rosetta750 Stroman228,3055,273,1133,95,651,119,0,417,1969-05-12T22:55:02-04:00,2022-01-11T01:04:56.624000-05:00,19236,4536,high,42
35,data/raw/longitudinalMCODEBreast/Erasmo545_Sto...,d44ac721-88ff-81cc-dd2f-7a30a1c1a221,Erasmo545 Stokes453,3201,155,1467,101,774,99,0,346,1954-12-16T03:11:58-05:00,2022-03-26T05:36:09-04:00,24572,4592,high,42
36,data/raw/longitudinalMCODEBreast/Delia459_Ande...,d7a86000-558f-c19e-d405-e5a86dfc7467,Delia459 Anderson154,2979,262,785,102,1047,61,4,354,1957-08-10T17:49:26-04:00,2011-08-20T18:04:26-04:00,19733,4727,high,42
37,data/raw/longitudinalMCODEBreast/Dan465_Pollic...,b73cbc40-ef87-47d5-08dc-4288048dbf1c,Dan465 Pollich983,3182,340,1050,87,771,31,0,462,1960-03-29T23:59:14-05:00,2022-06-08T03:41:01.937000-04:00,22715,4792,high,42
38,data/raw/longitudinalMCODEBreast/Shawana711_La...,f203e11d-5573-1624-69b8-af8436987b3e,Shawana711 Lakin515,3365,270,1322,95,791,37,3,404,1965-01-05T05:05:35-05:00,2022-06-29T11:37:21-04:00,20994,4812,high,42
39,data/raw/longitudinalMCODEBreast/Marcie463_Sto...,f18bd61f-f7be-ef83-db73-bbe83fb3391c,Marcie463 Stokes453,3427,255,1437,115,694,116,0,451,1944-02-05T09:56:40-04:00,2022-03-06T15:29:00-05:00,28519,4974,high,42
40,data/raw/longitudinalMCODEBreast/Paulita78_Hel...,66d5d38f-4e52-3896-822a-541e29cd965b,Paulita78 Heller342,3342,286,1167,116,892,58,0,426,1960-10-21T17:12:42-04:00,2022-04-27T20:25:25-04:00,22468,5029,high,42
41,data/raw/longitudinalMCODEBreast/Venita81_Mohr...,76edf896-139d-4308-ae25-44245b7a0bd3,Venita81 Mohr916,3452,221,1471,96,785,144,0,420,1960-06-16T05:01:40-04:00,2022-03-03T06:39:26.385000-05:00,22540,5044,high,42
42,data/raw/longitudinalMCODEBreast/Jaunita130_Me...,52241fcd-642a-1c0a-68ba-1d0e0531cbb2,Jaunita130 Metz686,3599,380,1301,106,714,68,0,542,1958-09-29T19:23:16-04:00,2022-06-20T20:31:31.188000-04:00,23275,5321,high,42
43,data/raw/longitudinalMCODEBreast/Shalanda398_B...,8dfff5d0-a8f1-4eac-3987-1670cc41239b,Shalanda398 Botsford977,4386,238,2236,85,713,162,3,507,1957-10-28T21:33:50-05:00,2022-03-22T13:11:28-04:00,23520,5910,high,42
44,data/raw/longitudinalMCODEBreast/Leroy603_Scha...,66e681dd-d945-9aba-95cb-d9606594cc9c,Leroy603 Schaefer657,4479,277,1672,87,1364,157,2,512,1942-12-15T01:24:08-04:00,2022-01-10T07:33:18-05:00,28881,6767,high,42
45,data/raw/longitudinalMCODEBreast/Rolando809_Gr...,e595cd98-c5d0-2a9d-ea2e-a1dc325005fa,Rolando809 Grant908,5233,174,3060,56,850,166,100,417,1958-09-23T20:53:43-04:00,2022-06-26T04:19:20-04:00,23286,6780,high,42
46,data/raw/longitudinalMCODEBreast/Ira784_Kunde5...,43a372f7-4803-75a8-9f34-45f6d377589f,Ira784 Kunde533,4866,243,2215,131,1293,119,1,517,1938-03-15T15:42:57-05:00,2017-06-06T16:57:57-04:00,28938,7086,high,42
47,data/raw/longitudinalMCODEBreast/Deandrea896_J...,3af995f1-02a5-07ee-5a7e-e2470a017f1e,Deandrea896 Johns824,5265,287,2693,169,812,284,0,634,1939-05-29T18:36:59-04:00,2011-07-04T18:51:59-04:00,26334,7372,high,42
48,data/raw/longitudinalMCODEBreast/Maricarmen445...,8629e803-6f0f-d985-e314-ff0808ac8bd4,Maricarmen445 Godínez202,6808,537,3291,119,993,449,1,789,1972-04-02T09:23:26-05:00,2022-06-30T15:02:04.638000-04:00,18351,9624,high,42
49,data/raw/longitudinalMCODEBreast/Mahalia897_Ni...,db62bf97-9977-e94c-94d1-46fa7abc524f,Mahalia897 Nikolaus26,10873,456,6661,271,1329,298,0,1275,1943-02-05T02:09:48-04:00,2022-04-01T05:18:37.517000-04:00,28910,14395,high,42

In [8]:
# Check bucket distribution
print("Bucket counts in full manifest:")
print(df["complexity_bucket"].value_counts())

# Sample 3 patients from each bucket (low, medium, high)
bucket_targets = {"low": 3, "medium": 3, "high": 3}
selected_rows = []

for bucket, n in bucket_targets.items():
    bucket_df = df[df["complexity_bucket"] == bucket].copy()
    if len(bucket_df) < n:
        raise ValueError(f"Not enough patients in bucket '{bucket}' to sample {n}.")

    # Random sample with a fixed seed for reproducibility
    sampled_bucket = bucket_df.sample(n=n, random_state=42)
    selected_rows.append(sampled_bucket)

selected_df = pd.concat(selected_rows).reset_index(drop=True)

print("\nSelected 9 patients (3 per bucket):")
display(selected_df[["patient_id", "patient_name", "complexity_bucket",
                     "n_resources", "complexity_score"]])

# Just the list of patient_ids for later use
selected_patient_ids = selected_df["patient_id"].tolist()
print("\nSelected patient_ids:", selected_patient_ids)

Bucket counts in full manifest:
complexity_bucket
low       17
high      17
medium    16
Name: count, dtype: int64

Selected 9 patients (3 per bucket):

,patient_id,patient_name,complexity_bucket,n_resources,complexity_score
0,d65197b3-056a-2136-b584-77f43c29da3f,Corrie32 Boyle917,low,230,317
1,f3739580-797d-ae04-eebf-aeddb2fc2f64,Florine959 Stark857,low,261,330
2,4736727e-63f4-071a-1516-a49310f5a052,Mónica985 Serrato62,low,436,602
3,29f6beee-162f-0113-7884-72245814693f,Eula461 Crooks415,medium,1854,2786
4,41681ed6-efc5-94c0-1bc0-f60b34dbd31b,Beth967 Cremin516,medium,1843,2800
5,aee216e6-cbe8-eaf2-3241-4bd1e8a01494,Deeann517 Torp761,medium,2191,3340
6,ecc4a7d0-8838-36b4-44ba-676d5a1f7927,Francina926 Von197,high,2945,4458
7,3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,Rosetta750 Stroman228,high,3055,4536
8,f203e11d-5573-1624-69b8-af8436987b3e,Shawana711 Lakin515,high,3365,4812

Selected patient_ids: ['d65197b3-056a-2136-b584-77f43c29da3f', 'f3739580-797d-ae04-eebf-aeddb2fc2f64', '4736727e-63f4-071a-1516-a49310f5a052', '29f6beee-162f-0113-7884-72245814693f', '41681ed6-efc5-94c0-1bc0-f60b34dbd31b', 'aee216e6-cbe8-eaf2-3241-4bd1e8a01494', 'ecc4a7d0-8838-36b4-44ba-676d5a1f7927', '3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678', 'f203e11d-5573-1624-69b8-af8436987b3e']

In [9]:
selected_patient_ids

['d65197b3-056a-2136-b584-77f43c29da3f',
 'f3739580-797d-ae04-eebf-aeddb2fc2f64',
 '4736727e-63f4-071a-1516-a49310f5a052',
 '29f6beee-162f-0113-7884-72245814693f',
 '41681ed6-efc5-94c0-1bc0-f60b34dbd31b',
 'aee216e6-cbe8-eaf2-3241-4bd1e8a01494',
 'ecc4a7d0-8838-36b4-44ba-676d5a1f7927',
 '3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678',
 'f203e11d-5573-1624-69b8-af8436987b3e']

In [ ]:
# looks at doc_type counts for selected patients, including oncology-flagged chunks

import sqlite3
import pandas as pd
from pathlib import Path
from IPython.display import display

db_path = Path("../data/retrieval/metadata.db")
conn = sqlite3.connect(db_path)

# Build a parameterized IN clause for SQLite
placeholders = ",".join(["?"] * len(selected_patient_ids))

doc_type_counts_selected = pd.read_sql_query(
    f"""
    SELECT
        chunks.patient_id,
        documents.doc_type,
        COUNT(*) AS n_chunks,
        SUM(CASE WHEN chunks.is_oncology = 1 THEN 1 ELSE 0 END) AS n_oncology_chunks
    FROM chunks
    JOIN documents ON chunks.document_id = documents.document_id
    WHERE chunks.patient_id IN ({placeholders})
    GROUP BY chunks.patient_id, documents.doc_type
    ORDER BY chunks.patient_id, n_chunks DESC
    """,
    conn,
    params=selected_patient_ids,
)

conn.close()

print("Long format: one row per selected patient/doc_type")
display(doc_type_counts_selected)

# Wide pivot: rows = selected patients, columns = doc_types, values = total chunk counts
doc_type_pivot_selected = (
    doc_type_counts_selected
    .pivot(index="patient_id", columns="doc_type", values="n_chunks")
    .fillna(0)
    .astype(int)
)

print("\nChunk counts by doc_type for each selected patient")
display(doc_type_pivot_selected)

# Oncology-only pivot
oncology_pivot_selected = (
    doc_type_counts_selected
    .pivot(index="patient_id", columns="doc_type", values="n_oncology_chunks")
    .fillna(0)
    .astype(int)
)

print("\nOncology-flagged chunk counts by doc_type for each selected patient")
display(oncology_pivot_selected)

# List of doc_types present per selected patient
doc_types_per_selected_patient = (
    doc_type_counts_selected[doc_type_counts_selected["n_chunks"] > 0]
    .groupby("patient_id")["doc_type"]
    .apply(list)
    .reset_index(name="doc_types")
)

print("\nDoc types present for each selected patient")
display(doc_types_per_selected_patient)

Long format: one row per selected patient/doc_type

,patient_id,doc_type,n_chunks,n_oncology_chunks
0,29f6beee-162f-0113-7884-72245814693f,observations,571,14
1,29f6beee-162f-0113-7884-72245814693f,procedures,408,37
2,29f6beee-162f-0113-7884-72245814693f,diagnostic_reports,284,0
3,29f6beee-162f-0113-7884-72245814693f,encounters,231,0
4,29f6beee-162f-0113-7884-72245814693f,oncology_timeline_events,53,53
...,...,...,...,...
76,f3739580-797d-ae04-eebf-aeddb2fc2f64,oncology_timeline_events,22,22
77,f3739580-797d-ae04-eebf-aeddb2fc2f64,medications,11,0
78,f3739580-797d-ae04-eebf-aeddb2fc2f64,patient_overview,9,9
79,f3739580-797d-ae04-eebf-aeddb2fc2f64,oncology_timeline,5,5
80,f3739580-797d-ae04-eebf-aeddb2fc2f64,conditions,5,2

Chunk counts by doc_type for each selected patient

doc_type,conditions,diagnostic_reports,encounters,medications,observations,oncology_timeline,oncology_timeline_events,patient_overview,procedures
patient_id,,,,,,,,,
29f6beee-162f-0113-7884-72245814693f,42,284,231,17,571,9,53,9,408
3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,95,417,273,119,1133,6,26,9,651
41681ed6-efc5-94c0-1bc0-f60b34dbd31b,56,250,197,41,565,9,49,9,465
4736727e-63f4-071a-1516-a49310f5a052,6,62,61,8,151,9,47,9,54
aee216e6-cbe8-eaf2-3241-4bd1e8a01494,50,336,287,45,597,9,52,9,500
d65197b3-056a-2136-b584-77f43c29da3f,2,28,27,20,80,6,29,9,27
ecc4a7d0-8838-36b4-44ba-676d5a1f7927,115,394,262,72,970,9,48,9,760
f203e11d-5573-1624-69b8-af8436987b3e,95,404,270,40,1322,9,52,9,791
f3739580-797d-ae04-eebf-aeddb2fc2f64,5,26,25,11,119,5,22,9,23

Oncology-flagged chunk counts by doc_type for each selected patient

doc_type,conditions,diagnostic_reports,encounters,medications,observations,oncology_timeline,oncology_timeline_events,patient_overview,procedures
patient_id,,,,,,,,,
29f6beee-162f-0113-7884-72245814693f,2,0,0,0,14,9,53,9,37
3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,2,0,0,0,14,6,26,0,10
41681ed6-efc5-94c0-1bc0-f60b34dbd31b,2,0,0,0,11,9,49,9,36
4736727e-63f4-071a-1516-a49310f5a052,1,0,0,0,11,9,47,9,35
aee216e6-cbe8-eaf2-3241-4bd1e8a01494,2,0,0,0,14,9,52,9,36
d65197b3-056a-2136-b584-77f43c29da3f,1,0,0,0,11,6,29,9,17
ecc4a7d0-8838-36b4-44ba-676d5a1f7927,2,0,0,0,10,9,48,9,36
f203e11d-5573-1624-69b8-af8436987b3e,2,0,0,0,14,9,52,0,36
f3739580-797d-ae04-eebf-aeddb2fc2f64,2,0,0,0,10,5,22,9,10

Doc types present for each selected patient

,patient_id,doc_types
0,29f6beee-162f-0113-7884-72245814693f,"[observations, procedures, diagnostic_reports,..."
1,3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,"[observations, procedures, diagnostic_reports,..."
2,41681ed6-efc5-94c0-1bc0-f60b34dbd31b,"[observations, procedures, diagnostic_reports,..."
3,4736727e-63f4-071a-1516-a49310f5a052,"[observations, diagnostic_reports, encounters,..."
4,aee216e6-cbe8-eaf2-3241-4bd1e8a01494,"[observations, procedures, diagnostic_reports,..."
5,d65197b3-056a-2136-b584-77f43c29da3f,"[observations, oncology_timeline_events, diagn..."
6,ecc4a7d0-8838-36b4-44ba-676d5a1f7927,"[observations, procedures, diagnostic_reports,..."
7,f203e11d-5573-1624-69b8-af8436987b3e,"[observations, procedures, diagnostic_reports,..."
8,f3739580-797d-ae04-eebf-aeddb2fc2f64,"[observations, diagnostic_reports, encounters,..."

In [ ]:
# check that all selected patients have the same set of doc_types (ignoring order)

import pandas as pd
from IPython.display import display

# Example: doc_types_per_selected_patient already computed, like:
# doc_types_per_selected_patient = (
#     doc_type_counts_selected[doc_type_counts_selected["n_chunks"] > 0]
#     .groupby("patient_id")["doc_type"]
#     .apply(list)
#     .reset_index(name="doc_types")
# )

# print("Doc types per selected patient:")
# display(doc_types_per_selected_patient)

# Convert each list of doc_types into a frozenset so order doesn't matter
doc_types_per_selected_patient["doc_types_set"] = (
    doc_types_per_selected_patient["doc_types"]
    .apply(lambda lst: frozenset(lst))
)

# Use the first patient's set as reference
reference_set = doc_types_per_selected_patient["doc_types_set"].iloc[0]
print("\nReference doc_types_set:", reference_set)

# Check equality against the reference
doc_types_per_selected_patient["matches_reference"] = (
    doc_types_per_selected_patient["doc_types_set"] == reference_set
)

print("\nEquality check vs reference:")
display(doc_types_per_selected_patient[["patient_id", "doc_types", "matches_reference"]])

# Summarize: how many distinct doc_types sets exist?
unique_sets = doc_types_per_selected_patient["doc_types_set"].unique()
print("\nNumber of distinct doc_types sets among selected patients:", len(unique_sets))

if len(unique_sets) > 1:
    print("Patients grouped by their doc_types_set:")
    # For readability, show each unique set and which patients have it
    for s in unique_sets:
        patients_with_set = doc_types_per_selected_patient[
            doc_types_per_selected_patient["doc_types_set"] == s
        ]["patient_id"].tolist()
        print(f"\nSet: {sorted(list(s))}")
        print("Patients:", patients_with_set)

Reference doc_types_set: frozenset({'oncology_timeline', 'procedures', 'observations', 'diagnostic_reports', 'encounters', 'oncology_timeline_events', 'medications', 'conditions', 'patient_overview'})

Equality check vs reference:

,patient_id,doc_types,matches_reference
0,29f6beee-162f-0113-7884-72245814693f,"[observations, procedures, diagnostic_reports,...",True
1,3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678,"[observations, procedures, diagnostic_reports,...",True
2,41681ed6-efc5-94c0-1bc0-f60b34dbd31b,"[observations, procedures, diagnostic_reports,...",True
3,4736727e-63f4-071a-1516-a49310f5a052,"[observations, diagnostic_reports, encounters,...",True
4,aee216e6-cbe8-eaf2-3241-4bd1e8a01494,"[observations, procedures, diagnostic_reports,...",True
5,d65197b3-056a-2136-b584-77f43c29da3f,"[observations, oncology_timeline_events, diagn...",True
6,ecc4a7d0-8838-36b4-44ba-676d5a1f7927,"[observations, procedures, diagnostic_reports,...",True
7,f203e11d-5573-1624-69b8-af8436987b3e,"[observations, procedures, diagnostic_reports,...",True
8,f3739580-797d-ae04-eebf-aeddb2fc2f64,"[observations, diagnostic_reports, encounters,...",True

Number of distinct doc_types sets among selected patients: 1

In [12]:
# look at all oncology chunks in chunks_df:

import sqlite3
import pandas as pd
from pathlib import Path

db_path = Path("../data/retrieval/metadata.db")
patient_ids = selected_patient_ids

conn = sqlite3.connect(db_path)

# Multiple patient_ids: build an IN (...) placeholder list.
if not patient_ids:
    chunks_df = pd.DataFrame()  # avoid invalid SQL: IN ()
else:
    placeholders = ",".join(["?"] * len(patient_ids))
    query = f"""
    SELECT
        chunks.patient_id,
        documents.doc_type,
        documents.title,
        chunks.heading,
        chunks.chunk_id,
        chunks.is_oncology,
        chunks.chunk_text
    FROM chunks
    JOIN documents ON chunks.document_id = documents.document_id
    WHERE chunks.patient_id IN ({placeholders})
    """
    chunks_df = pd.read_sql_query(query, conn, params=patient_ids)

conn.close()

display(chunks_df.head())
print("Number of rows:", len(chunks_df))

onc_chunks = chunks_df[chunks_df["is_oncology"] == 1]
display(onc_chunks.head())
print("Number of oncology chunks:", len(onc_chunks))

,patient_id,doc_type,title,heading,chunk_id,is_oncology,chunk_text
0,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,82fbc5fb0df955ed9b5861c956dd9d5cdd0a1aa8,1,patient_id: 29f6beee-162f-0113-7884-7224581469...
1,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,cd9bf67f542dee2c5c6eb4e889086745d239ff7b,0,patient_id: 29f6beee-162f-0113-7884-7224581469...
2,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,c6f4af530450ec4d38f7f478693b4d62c2b3467c,0,patient_id: 29f6beee-162f-0113-7884-7224581469...
3,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,9d5bdbca525ce28a75b1ad7deff73853cc1b20eb,0,patient_id: 29f6beee-162f-0113-7884-7224581469...
4,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,250fb82c086a015ec8fe85d5feeb46806e632e86,0,patient_id: 29f6beee-162f-0113-7884-7224581469...

Number of rows: 14390

,patient_id,doc_type,title,heading,chunk_id,is_oncology,chunk_text
0,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,82fbc5fb0df955ed9b5861c956dd9d5cdd0a1aa8,1,patient_id: 29f6beee-162f-0113-7884-7224581469...
21,29f6beee-162f-0113-7884-72245814693f,conditions,conditions.csv,conditions,34e083fbe248b34ab7ff75e989fc91da40a6b511,1,patient_id: 29f6beee-162f-0113-7884-7224581469...
931,29f6beee-162f-0113-7884-72245814693f,observations,observations.csv,observations,6c44d78bfe33c70133759592f49f88f9cd26734c,1,patient_id: 29f6beee-162f-0113-7884-7224581469...
932,29f6beee-162f-0113-7884-72245814693f,observations,observations.csv,observations,4f181909c2fad14ebbdc20f28f1af14d5dfb89f9,1,patient_id: 29f6beee-162f-0113-7884-7224581469...
933,29f6beee-162f-0113-7884-72245814693f,observations,observations.csv,observations,b02dbcb96bafeb63dc73b3c40a9f184cb0e781bf,1,patient_id: 29f6beee-162f-0113-7884-7224581469...

Number of oncology chunks: 890

In [13]:
onc_chunks["doc_type"].value_counts()

doc_type
oncology_timeline_events    378
procedures                  253
observations                109
oncology_timeline            71
patient_overview             63
conditions                   16
Name: count, dtype: int64

In [14]:
onc_chunks.groupby("patient_id")["doc_type"].count()

patient_id
29f6beee-162f-0113-7884-72245814693f    124
3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678     58
41681ed6-efc5-94c0-1bc0-f60b34dbd31b    116
4736727e-63f4-071a-1516-a49310f5a052    112
aee216e6-cbe8-eaf2-3241-4bd1e8a01494    122
d65197b3-056a-2136-b584-77f43c29da3f     73
ecc4a7d0-8838-36b4-44ba-676d5a1f7927    114
f203e11d-5573-1624-69b8-af8436987b3e    113
f3739580-797d-ae04-eebf-aeddb2fc2f64     58
Name: doc_type, dtype: int64

In [15]:
onc_chunks.groupby("doc_type")["patient_id"].value_counts()

doc_type                  patient_id
conditions                29f6beee-162f-0113-7884-72245814693f     2
                          ecc4a7d0-8838-36b4-44ba-676d5a1f7927     2
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b     2
                          f203e11d-5573-1624-69b8-af8436987b3e     2
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494     2
                          f3739580-797d-ae04-eebf-aeddb2fc2f64     2
                          3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678     2
                          d65197b3-056a-2136-b584-77f43c29da3f     1
                          4736727e-63f4-071a-1516-a49310f5a052     1
observations              3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678    14
                          f203e11d-5573-1624-69b8-af8436987b3e    14
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494    14
                          29f6beee-162f-0113-7884-72245814693f    14
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b    11
                          d65197b3-056a-2136-b584-77f43c29da3f    11
                          4736727e-63f4-071a-1516-a49310f5a052    11
                          ecc4a7d0-8838-36b4-44ba-676d5a1f7927    10
                          f3739580-797d-ae04-eebf-aeddb2fc2f64    10
oncology_timeline         f203e11d-5573-1624-69b8-af8436987b3e     9
                          ecc4a7d0-8838-36b4-44ba-676d5a1f7927     9
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494     9
                          4736727e-63f4-071a-1516-a49310f5a052     9
                          29f6beee-162f-0113-7884-72245814693f     9
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b     9
                          d65197b3-056a-2136-b584-77f43c29da3f     6
                          3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678     6
                          f3739580-797d-ae04-eebf-aeddb2fc2f64     5
oncology_timeline_events  29f6beee-162f-0113-7884-72245814693f    53
                          f203e11d-5573-1624-69b8-af8436987b3e    52
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494    52
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b    49
                          ecc4a7d0-8838-36b4-44ba-676d5a1f7927    48
                          4736727e-63f4-071a-1516-a49310f5a052    47
                          d65197b3-056a-2136-b584-77f43c29da3f    29
                          3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678    26
                          f3739580-797d-ae04-eebf-aeddb2fc2f64    22
patient_overview          ecc4a7d0-8838-36b4-44ba-676d5a1f7927     9
                          4736727e-63f4-071a-1516-a49310f5a052     9
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b     9
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494     9
                          f3739580-797d-ae04-eebf-aeddb2fc2f64     9
                          29f6beee-162f-0113-7884-72245814693f     9
                          d65197b3-056a-2136-b584-77f43c29da3f     9
procedures                29f6beee-162f-0113-7884-72245814693f    37
                          f203e11d-5573-1624-69b8-af8436987b3e    36
                          ecc4a7d0-8838-36b4-44ba-676d5a1f7927    36
                          41681ed6-efc5-94c0-1bc0-f60b34dbd31b    36
                          aee216e6-cbe8-eaf2-3241-4bd1e8a01494    36
                          4736727e-63f4-071a-1516-a49310f5a052    35
                          d65197b3-056a-2136-b584-77f43c29da3f    17
                          3a1c7c7b-0f87-e7ba-f2ed-1b0882fe3678    10
                          f3739580-797d-ae04-eebf-aeddb2fc2f64    10
Name: count, dtype: int64

In [16]:
chunks_df.columns

Index(['patient_id', 'doc_type', 'title', 'heading', 'chunk_id', 'is_oncology',
       'chunk_text'],
      dtype='str')

# Shared set of question

That’s a very good sign: it means all 9 selected patients have the **same set of document types** (even if the order in the lists differs).

Practically, this gives you a clean foundation for your evaluation set:

- Every selected patient has all of:
  - `patient_overview`
  - `conditions`
  - `medications`
  - `procedures`
  - `observations`
  - `diagnostic_reports`
  - `encounters`
  - `oncology_timeline_events`
  - `oncology_timeline` (plus whatever else is in that set).

So you can safely design a **shared set of question templates** and apply them across all 9 patients, only skipping oncology-specific ones for those who truly have no oncology-flagged content. [youtube](https://www.youtube.com/watch?v=IYx4O42dHd0)

A natural next step, given this:

- Define 3–4 question types that map onto these doc_types (e.g., overview, conditions, medications, oncology history).
- Then, for each of your 9 patients, label gold_chunk_ids for those questions using the doc_type + is_oncology filters you already have.

If you want, I can propose a concrete list of 4 question templates that directly correspond to these doc_types and are suitable for all 9 patients.

Great — here’s a concrete 4-question core set plus a 5-question extended set, both designed to work across all 9 selected patients, along with how to choose `gold_chunk_ids` for each. Because all patients share the same doc_types, you can apply this uniformly. 

### Core 4-question set (recommended baseline)

Use this for your main evaluation; it balances general and oncology content and stays relatively easy to annotate.

1. **Patient overview**

   - Question:  
     “Give a concise overview of this patient’s medical background and current care context.”
   - Primary doc_types to draw gold chunks from:  
     `patient_overview`, `encounters`, `conditions`, `oncology_timeline_events`. 
   - Gold chunk guidance:
     - Include 2–4 chunks that together cover:
       - Key chronic conditions. 
       - Major past procedures or events if they define the patient’s course. 
       - A high-level oncology context if applicable (e.g., diagnosis, line of therapy). 
     - Prefer chunks that are explicitly summary-like (e.g., overview notes) over raw measurements.

2. **Conditions**

   - Question:  
     “What are the patient’s main diagnosed conditions?”
   - Primary doc_types:  
     `conditions`, possibly `encounters` or `patient_overview` if they contain canonical lists. 
   - Gold chunk guidance:
     - Select chunks that list named diagnoses (problem lists, diagnosis sections, structured condition records). 
     - If conditions evolve (e.g., disease progression or resolved conditions), include chunks that clearly mark the current status.

3. **Medications**

   - Question:  
     “What medications is the patient taking or has recently taken?”
   - Primary doc_types:  
     `medications`, optionally `encounters` or `oncology_timeline_events` if they record regimens. 
   - Gold chunk guidance:
     - Focus on chunks that list active or recent meds (lists, med history sections). 
     - If oncology regimens are recorded in timeline events rather than meds, include those chunks too. 

4. **Oncology timeline**

   - Question:  
     “Summarize the patient’s oncology-related timeline, including major events and treatments.”
   - Primary doc_types:  
     `oncology_timeline_events`, `oncology_timeline`, plus supporting `encounters` or `diagnostic_reports` if needed. 
   - Gold chunk guidance:
     - Choose 3–6 chunks covering:
       - Initial diagnosis/first cancer-related event.
       - Key treatment starts/changes (lines of therapy, major procedures). 
       - Notable response/progression events or critical findings (e.g., scan results summaries). 
     - Try to keep the subset coherent and roughly chronological, so a model could reconstruct a timeline from them.

### Extended 5-question set (adds a synthesis question)

For a richer benchmark, add this fifth question; it forces multi-doc-type reasoning.

5. **Cross-document clinical priorities**

   - Question:  
     “What clinical issues appear to be most important for this patient right now?”
   - Primary doc_types:  
     `conditions`, `medications`, `encounters`, `observations`, `diagnostic_reports`, and `oncology_timeline_events`. 
   - Gold chunk guidance:
     - Pick 4–8 chunks such that:
       - Each chunk contributes a distinct piece of evidence (e.g., a condition, a treatment, a key observation/report). 
       - Together they justify why certain issues are “most important” (e.g., active malignancy on treatment, uncontrolled comorbidity, acute complication). 
     - Explicitly favor chunks that are:
       - Recent in time.
       - Clearly interpretable (e.g., summary sections rather than isolated lab values), unless a lab/report is itself critical.

### How to pick gold_chunk_ids in practice

For each patient and each question:

- Step 1: Filter by doc_type and (if you have it) `is_oncology` flag or recency indicators. 
- Step 2: From the filtered subset, manually inspect and choose only the chunks that:
  - Directly answer the question.
  - Are reasonably self-contained (the model doesn’t need many unrelated chunks to interpret them).
- Step 3: Store:
  - `question_text`
  - `patient_id`
  - `gold_chunk_ids` (list of chunk IDs)
  - Optionally a short `rationale` free-text explaining why these chunks were selected (can be handy for later analysis).

This gives you a consistent scheme across all 9 patients: every patient gets the same 4 core questions, and optionally the 5th synthesis question, with gold_chunk_ids drawn from matching doc_types. 

Do you already have a column that marks “recent” vs “historical” chunks (e.g., encounter date), or should I suggest a simple heuristic for recency using only what’s in your `chunks` table?

#### 1. **Patient overview**

This filters candidate chunks for one patient for the Patient Overview question, prioritizing summary-like doc types and creating a readable preview. Filtering with isin(...) and sorting with sort_values(...) are standard Pandas patterns for this kind of review table:

In [ ]:
import pandas as pd
from IPython.display import display

QUESTION_TYPE = "patient_overview"
QUESTION_TEXT = "Give a concise overview of this patient’s medical background and current care context."

overview_doc_types = ["conditions"]
overview_headings = [
    "Recent Condition",
    "Recent Results",
    "Procedures",
]

# Boolean mask for relevant chunks according to your rule
mask_conditions = chunks_df["doc_type"] == "conditions"
mask_headings = chunks_df["heading"].isin(overview_headings)

relevant_mask = mask_conditions | mask_headings

patient_overview_gold = (
    chunks_df.loc[relevant_mask, ["patient_id", "chunk_id"]]
    .groupby("patient_id")["chunk_id"]
    .apply(list)
    .reset_index()
    .rename(columns={"chunk_id": "gold_chunk_ids"})
)

patient_overview_gold["question_type"] = QUESTION_TYPE
patient_overview_gold["question_text"] = QUESTION_TEXT

# Optional: reorder columns for clarity
patient_overview_gold = patient_overview_gold[
    ["patient_id", "question_type", "question_text", "gold_chunk_ids"]
]

display(patient_overview_gold)